### ISSUE TITLE
Community Partner Campaign for PyConf Hyderabad 2020

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#10]
- [ ] List out communities to Reach Out
- [ ] Define terms & CoC
- [ ] Draft an email and reach out
- [ ] Shortlist Communities which can be partners
- [ ] Get them listed as Community Partners
- [ ] Provide them booth slot on Hopin for a specific time slot during the conference

**Comment by inovizz** [comment]
Listing a few communities which I know
- [ ] PyDelhi
- [ ] PythonPune
- [ ] BangPypers
- [ ] Pune Developers Group
- [ ] GDG Hyderabad
- [ ] Coderplex
- [ ] Collabnix
- [ ] Docker Bangalore
- [ ] Open Source Bangalore
- [ ] Co-learning Lounge
- [ ] ThoughtWorks Hyderabad
- [ ] Hyderabad DataScience Group

**Comment by GoelJatin** [comment]
Email draft - @inovizz @ramanathanhari , can you please review the draft. I'll start sending emails to the communities

<hr>

Hi {{ name }},

Hope you're doing well. I'm writing to you on behalf of the **Hyderabad Python User Group (HydPy)[1]** about our 3rd edition of **PyConf Hyderabad 2020 (Virtual)[2]**. It's a 2 day multi-track conference happening on 5th and 6th December.

This year we've made few changes to the conference format which includes **NO Sponsors** but instead of that we've **Community Partners**, to promote Python and other OSS communities in India.

Check out the PPT attached for more details about the conference and the Community Partner Program.

We would love to have you and the {{ community_name }} team collaborate and support community initiatives like this. Looking forward to hearing from you.

And thank you for all you do in the community :)

[1] - https://www.hydpy.org/
[2] - https://pyconf.hydpy.org/2020/

Best Regards,
Jatin Goel
(On behalf of Team PyConf Hyd)

**Comment by inovizz** [comment]
Looks good to me.

**Comment by inovizz** [comment]
![community-partner](https://user-images.githubusercontent.com/3849885/97802015-97907200-1c66-11eb-873a-cde32290a689.png)

Poster for social media.

**Comment by GoelJatin** [comment]
Sent out the emails to the initial list and will try to get the contacts for the other communities. SM announcement is pending

**Comment by kalyan678** [comment]
@inovizz & @GoelJatin  I was not able to add both image and PPT in twitter because it was not accepting. Instead I have given the link of PPT which can be accessible to them. 
Finally posted in all SM channels. Thank you!

**Comment by inovizz** [comment]
![pyconf_poster](https://user-images.githubusercontent.com/3849885/98244948-39c99600-1f96-11eb-8da2-dbf3e580dd79.png)

**Comment by GoelJatin** [comment]
we can close this
